package permissions.db.repos;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

import permissions.db.PagingInfo;
import permissions.db.RoleRepository;
import permissions.domain.Role;

public class HsqlRoleRepository implements RoleRepository{

	private Connection connection;
	
	private String insertSql ="INSERT INTO role(name) VALUES(?)"; 
	private String selectSql ="SELECT * FROM role LIMIT(?)";
	private String selectByIdSql ="SELECT * FROM role WHERE id=?";
	private String selectByNameSql ="SELECT * FROM role WHERE Name=? LIMIT(?,?)";
	private String deleteSql = "DELETE FROM role WHERE id=?";
	private String updateSql = "UPDATE role SET (name)=(?) WHERE id=?";
	
	private PreparedStatement insert;
	private PreparedStatement select;
	private PreparedStatement selectById;
	private PreparedStatement selectByName;
	private PreparedStatement delete;
	private PreparedStatement update;
	

	private String createRoleTable =""
			+ "CREATE TABLE Role("
			+ "id bigint GENERATED BY DEFAULT AS IDENTITY,"
			+ "name VARCHAR(20),"
			+ ")";
	
	
	public HsqlRoleRepository(Connection connection){
		this.connection=connection;
		
		try{
			

			insert = connection.prepareStatement(insertSql);
			select = connection.prepareStatement(selectSql);
			selectById = connection.prepareStatement(selectByIdSql);
			selectByName = connection.prepareStatement(selectByNameSql);
			delete = connection.prepareStatement(deleteSql);
			update = connection.prepareStatement(updateSql);
			
			
			ResultSet rs = connection.getMetaData().getTables(null, null, null, null);
			
			boolean tableExists =false;
			while(rs.next())
			{
				if(rs.getString("TABLE_NAME").equalsIgnoreCase("Role")){
					tableExists=true;
					break;
				}
			}
			if(!tableExists){
				Statement createTable = connection.createStatement();
				createTable.executeUpdate(createRoleTable);
			}
		}catch(SQLException ex){
			ex.printStackTrace();
		}
		
	}
	
	
	public Role withId(int id) {
		Role result = null;
		try {
			selectById.setInt(1, id);
			ResultSet rs = selectById.executeQuery();
			while(rs.next()){
				Role role = new Role();
				role.setName(rs.getString("name"));
				role.setId(rs.getInt("id"));
				result = role;
				break;
			}
		} catch (SQLException e) {
			e.printStackTrace();
		}
		return result;
	}

	public List<Role> allOnPage(PagingInfo page) {
List<Role> result = new ArrayList<Role>();
		
		try {
			select.setInt(1, page.getCurrentPage()*page.getSize());
			select.setInt(2, page.getSize());
			ResultSet rs = select.executeQuery();
			while(rs.next()){
				Role role = new Role();
				role.setName(rs.getString("name"));
				role.setId(rs.getInt("id"));
				result.add(role);
			}
		} catch (SQLException e) {
			e.printStackTrace();
		}
		return result;
	}

	public void add(Role role) {
		try {
			insert.setString(1, role.getName());
			
			insert.executeUpdate();
		} catch (SQLException e) {
			e.printStackTrace();
		}
		
	}

	public void modify(Role r) {
		try {
			update.setString(1, r.getName());
			update.setInt(2, r.getId());
			update.executeUpdate();
		} catch (SQLException e) {
			e.printStackTrace();
		}
		
	}

	public void remove(Role r) {
		try {
			delete.setInt(1, r.getId());
			delete.executeUpdate();
		} catch (SQLException e) {
			e.printStackTrace();
		}
		
	}



	public List<Role> withName(String name, PagingInfo page) {

		List<Role> result = new ArrayList<Role>();
		try {
			selectByName.setString(1, name);
			selectByName.setInt(2, page.getCurrentPage()*page.getSize());
			selectByName.setInt(3, page.getSize());
			ResultSet rs = selectByName.executeQuery();
			while(rs.next()){
				Role role = new Role();
				role.setName(rs.getString("name"));
				role.setId(rs.getInt("id"));
				result.add(role);
			}
		} catch (SQLException e) {
			e.printStackTrace();
		}
		return result;
	}


}